apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-208315/pipeline:d0b78d534e7b2a48b9b7cc15d3007ece3003e075
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
